// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package server

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockWalletStorage creates a new instance of MockWalletStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWalletStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWalletStorage {
	mock := &MockWalletStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWalletStorage is an autogenerated mock type for the WalletStorage type
type MockWalletStorage struct {
	mock.Mock
}

type MockWalletStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWalletStorage) EXPECT() *MockWalletStorage_Expecter {
	return &MockWalletStorage_Expecter{mock: &_m.Mock}
}

// ChangeBalance provides a mock function for the type MockWalletStorage
func (_mock *MockWalletStorage) ChangeBalance(sum float64, uuid string) (bool, error) {
	ret := _mock.Called(sum, uuid)

	if len(ret) == 0 {
		panic("no return value specified for ChangeBalance")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(float64, string) (bool, error)); ok {
		return returnFunc(sum, uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(float64, string) bool); ok {
		r0 = returnFunc(sum, uuid)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(float64, string) error); ok {
		r1 = returnFunc(sum, uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletStorage_ChangeBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeBalance'
type MockWalletStorage_ChangeBalance_Call struct {
	*mock.Call
}

// ChangeBalance is a helper method to define mock.On call
//   - sum float64
//   - uuid string
func (_e *MockWalletStorage_Expecter) ChangeBalance(sum interface{}, uuid interface{}) *MockWalletStorage_ChangeBalance_Call {
	return &MockWalletStorage_ChangeBalance_Call{Call: _e.mock.On("ChangeBalance", sum, uuid)}
}

func (_c *MockWalletStorage_ChangeBalance_Call) Run(run func(sum float64, uuid string)) *MockWalletStorage_ChangeBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWalletStorage_ChangeBalance_Call) Return(b bool, err error) *MockWalletStorage_ChangeBalance_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockWalletStorage_ChangeBalance_Call) RunAndReturn(run func(sum float64, uuid string) (bool, error)) *MockWalletStorage_ChangeBalance_Call {
	_c.Call.Return(run)
	return _c
}

// Check provides a mock function for the type MockWalletStorage
func (_mock *MockWalletStorage) Check(uuid string) (bool, error) {
	ret := _mock.Called(uuid)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, error)); ok {
		return returnFunc(uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(uuid)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(uuid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWalletStorage_Check_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Check'
type MockWalletStorage_Check_Call struct {
	*mock.Call
}

// Check is a helper method to define mock.On call
//   - uuid string
func (_e *MockWalletStorage_Expecter) Check(uuid interface{}) *MockWalletStorage_Check_Call {
	return &MockWalletStorage_Check_Call{Call: _e.mock.On("Check", uuid)}
}

func (_c *MockWalletStorage_Check_Call) Run(run func(uuid string)) *MockWalletStorage_Check_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWalletStorage_Check_Call) Return(b bool, err error) *MockWalletStorage_Check_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockWalletStorage_Check_Call) RunAndReturn(run func(uuid string) (bool, error)) *MockWalletStorage_Check_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWallet provides a mock function for the type MockWalletStorage
func (_mock *MockWalletStorage) CreateWallet(uuid string) error {
	ret := _mock.Called(uuid)

	if len(ret) == 0 {
		panic("no return value specified for CreateWallet")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(uuid)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWalletStorage_CreateWallet_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWallet'
type MockWalletStorage_CreateWallet_Call struct {
	*mock.Call
}

// CreateWallet is a helper method to define mock.On call
//   - uuid string
func (_e *MockWalletStorage_Expecter) CreateWallet(uuid interface{}) *MockWalletStorage_CreateWallet_Call {
	return &MockWalletStorage_CreateWallet_Call{Call: _e.mock.On("CreateWallet", uuid)}
}

func (_c *MockWalletStorage_CreateWallet_Call) Run(run func(uuid string)) *MockWalletStorage_CreateWallet_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWalletStorage_CreateWallet_Call) Return(err error) *MockWalletStorage_CreateWallet_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWalletStorage_CreateWallet_Call) RunAndReturn(run func(uuid string) error) *MockWalletStorage_CreateWallet_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockWalletStorage
func (_mock *MockWalletStorage) Get(uuid string) (bool, float64, error) {
	ret := _mock.Called(uuid)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 bool
	var r1 float64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (bool, float64, error)); ok {
		return returnFunc(uuid)
	}
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(uuid)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(string) float64); ok {
		r1 = returnFunc(uuid)
	} else {
		r1 = ret.Get(1).(float64)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(uuid)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockWalletStorage_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockWalletStorage_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - uuid string
func (_e *MockWalletStorage_Expecter) Get(uuid interface{}) *MockWalletStorage_Get_Call {
	return &MockWalletStorage_Get_Call{Call: _e.mock.On("Get", uuid)}
}

func (_c *MockWalletStorage_Get_Call) Run(run func(uuid string)) *MockWalletStorage_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWalletStorage_Get_Call) Return(b bool, f float64, err error) *MockWalletStorage_Get_Call {
	_c.Call.Return(b, f, err)
	return _c
}

func (_c *MockWalletStorage_Get_Call) RunAndReturn(run func(uuid string) (bool, float64, error)) *MockWalletStorage_Get_Call {
	_c.Call.Return(run)
	return _c
}
